version: '3.8'

services:
  desafio-api:
    build:
      context: .
      dockerfile: desafio-api/Dockerfile
    image: desafio-api
    ports:
      - "8080:8080"    # Mapeia a porta 8080 do container para a porta 8080 do host
      - "8081:8081"    # Mapeia a porta 8081 do container para a porta 8081 do host (se necessário)
    depends_on:
      desafio-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Ajuste a string de conexão para apontar para o serviço 'desafio-db'
      - ConnectionStrings__DefaultConnection=Host=desafio-db;Port=5432;Database=postgres;Username=desafio;Password=desafio

  desafio-db:
    image: postgres:14
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U desafio"]
      interval: 10s
      timeout: 5s
      retries: 5
