version: '3.8'

services:
  desafio-api:
    build:
      context: .
      dockerfile: desafio-api/desafio-api/Dockerfile
    image: desafio-api
    ports:
      - "8080:8080"   
    depends_on:
      desafio-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=desafio-db;Port=5432;Database=postgres;Username=desafio;Password=desafio

  desafio-db:
    image: postgres:14
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"

  desafio-front:
    build:
      context: ./desafio-front
      dockerfile: Dockerfile
    image: desafio-front
    ports:
      - "5173:5173"
    depends_on:
      - desafio-api

